name: ALZ-Bicep-1 Workflow


trigger:
  branches:
    include:
      - "main"
  paths:
    include:
      - "config/custom-parameters/managementGroups.parameters.all.json"
      - "config/custom-parameters/resourceGroupLoggingAndSentinel.parameters.all.json"
      - "config/custom-parameters/logging.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
      - "config/custom-parameters/mgDiagSettingsAll.parameters.all.json"


variables:
  SERVICE_CONNECTION_NAME: ""
  LOCATION: ""
  UPSTREAM_RELEASE_VERSION: ""
  MANAGEMENT_SUBSCRIPTION_ID: ""
  TOP_LEVEL_MG_PREFIX: ""


jobs:
  - job: ALZ_Bicep_1_Workflow_Job
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout Repo

      - task: AzurePowerShell@5
        displayName: "Management Groups Deployment"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZManagementGroups.ps1

      - task: AzurePowerShell@5
        displayName: "Logging and Sentinel Resource Group Deployment"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZLoggingAndSentinelResourceGroup.ps1

      - task: AzurePowerShell@5
        displayName: "Logging and Sentinel Deployment"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZLoggingAndSentinel.ps1

      - task: AzurePowerShell@5
        displayName: "Custom Policy Definitions Deployment"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZCustomPolicyDefinitions.ps1

      - task: AzurePowerShell@5
        displayName: "Custom Role Definitions Deployment"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZCustomRoleDefinitions.ps1

      - task: AzurePowerShell@5
        displayName: "Custom Management Group Diagnostic Settings"
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION_NAME }}
          azurePowerShellVersion: "LatestVersion"
          pwsh: true
          ScriptType: "InlineScript"
          Inline: |
            .\accelerator\pipeline-scripts\Deploy-ALZMGDiagnosticSettings.ps1
