name: ALZ-Bicep-3 Workflow

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/subscriptionPlacement.parameters.all.json"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: ""
  UPSTREAM_RELEASE_VERSION: ""
  TOP_LEVEL_MG_PREFIX: ""

jobs:
  ALZ_Bicep_3_Workflow_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Deploy Subscription Placement"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZSubscriptionPlacement.ps1
          azPSVersion: "latest"
