name: Bug Report
description: File a bug report
title: "[PLACEHOLDER] - Place a descriptive title here"
labels: ["bug"]
assignees:
  - test
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Provide a clear and concise description of the bug, including deployment details.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: correlation-id
    attributes:
      label: Please provide the correlation id associated with your error or bug. You can use the example here on how to find it https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-is-expected
    attributes:
      label: What was the expected outcome?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: checkboxes
    id: previous-checks
    attributes:
      label: check previous github issues
      description: By submitting this issue, you confirm that you have done a search for this issue in the current issue list https://github.com/Azure/ALZ-Bicep/issues?q=is%3Aissue+sort%3Aupdated-desc+
      options:
        - label: I have searched previous issues for this item
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct] https://github.com/Azure/ALZ-Bicep/blob/main/CODE_OF_CONDUCT.md
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
