name: Feature Request \U0001F4A1
description: Request a new feature!
title: " \U0001F4A1 [PLACEHOLDER] - Place a descriptive title here"
labels: ["feature"]
assignees:
  - test
body:
  - type: markdown
    attributes:
      value: |
        We always appreciate the community involvement! Request the feature below
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe the feature end to end, including deployment scenario details under which the feature would occur.
      value: "New Feature Details"
    validations:
      required: true
  - type: textarea
    id: feature-why
    attributes:
      label: Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?
    validations:
      required: true
  - type: textarea
    id: correlation-id
    attributes:
      label: Please provide the correlation id associated with your error or bug. You can use the example here on how to find it https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history?tabs=azure-portal
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: feature-alternatives
    attributes:
      label: Can you describe any alternatives that you have taken since this feature does not exist?
    validations:
      required: false
  - type: textarea
    id: feature-implementation
    attributes:
      label: Feature Implementation
      description: Did you successfully implement the feature on your own? Do you have code to share? Link to your branch, if applicable.
      render: Shell
    validations:
      required: false
  - type: checkboxes
    id: previous-checks
    attributes:
      label: check previous github issues
      description: By submitting this issue, you confirm that you have done a search for this issue in the current issue list (https://github.com/Azure/ALZ-Bicep/issues?q=is%3Aissue+sort%3Aupdated-desc+)
      options:
        - label: I have searched previous issues for this item
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Azure/ALZ-Bicep/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
