trigger: none

variables:
 - group: csu-bicep-environment

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/.github/azFunction/AzFunctionCode"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

- task: Bash@3
  displayName: Login to Azure
  name: git_azlogin
  inputs:
    targetType: 'inline'
    script: |
      az login --service-principal --username $(azclilogin) --password $(azclipwd) --tenant $(azclitenant)

- task: Bash@3    
  displayName: Deploy Base Azure Function
  name: create_az_function
  inputs:
    targetType: 'inline'
    script: |
      az deployment group create --resource-group cancelsubscription --template-file .github/azFunction/AzFunctionInfrastructure/main.bicep --parameters parAzFunctionName=$(cancelsubfunctionname)

- task: AzureFunctionApp@1 
  displayName: "Deploy Functions to base"
  inputs:
    azureSubscription: 'azserviceconnection'
    appType: functionAppLinux 
    appName: $(cancelsubfunctionname)
    package: $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip

- task: Bash@3    
  displayName: Az CLI create Role Assignment to Tenant root group
  name: create_role_assign_tenant
  inputs:
    targetType: 'inline'
    script: |
      az deployment mg create --template-file .github/azFunction/AzFunctionInfrastructure/rbac.bicep --parameters parAzFunctionName=$(cancelsubfunctionname) parAzFunctionSubscriptionId=$(cancelsubid) --location $(Location) --management-group-id $(azclitenant) --name setrbac


