name: Sync Issues to Azure DevOps Work Items

on:
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    if: github.repository == 'Azure/ALZ-Bicep'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: GitHub/ADO Sync
        uses: a11smiles/GitSync@74d80b4ef67578135781e76ee1d4add1b98969b1 # v1.2.3
        env:
          ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
          config_file: './.github/actions-config/gh-ado-sync-config.json'
        with:
          ado: ${{ secrets.ADO_MAPPINGS_HANDLES }}
